version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/inference_server
hooks:
  BeforeInstall:
    - location: deployment_scripts/before_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: deployment_scripts/start_server.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: deployment_scripts/stop_server.sh
      timeout: 300
      runas: ubuntu
