version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/yhat
hooks:
  BeforeInstall:
    - location: deployment_scripts/before_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deployment_scripts/start_server.sh
      timeout: 300
      runas: ubutnu
  ApplicationStop:
    - location: deployment_scripts/stop_server.sh
      timeout: 300
      runas: ubutnu
