version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Getting Started

  pre_build:
    commands:
      - echo Prebuild started on `date`
      - apt-get update
      - apt-get -y install python3-venv
      - apt-get -y install libssl-dev
      - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
      - export PATH=$PATH:$HOME/.poetry/bin
      - python -m venv venv
      - . venv/bin/activate
      - poetry install --no-dev
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo "PARAM_STORE=$PARAM_STORE" > .env
      - echo "AWS_REGION_NAME=$AWS_REGION_NAME" >> .env
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
